import { FlowNode, FlowConnection } from "./types";

let _nid = 0;
function nid(): string {
  return "n" + ++_nid;
}

export function getInitialNodes(): FlowNode[] {
  _nid = 0;
  return [
    {
      id: nid(),
      type: "start",
      x: 500,
      y: 30,
      label: "Customer Starts Shopping",
      detail: "Visits Revibe store (Saudi Arabia, UAE, South Africa, or Philippines)",
      actor: "system",
      tools: ["Shopify", "Revibe Store"],
      sla: "Instant",
    },
    {
      id: nid(),
      type: "step",
      x: 460,
      y: 140,
      label: "Browses & Selects Product",
      detail: "Customer views refurbished phones, tablets, or accessories and picks a product",
      actor: "revibe",
      tools: ["Catalog", "Search Engine"],
      internalStage: "Product Discovery",
      externalStage: "Browsing",
    },
    {
      id: nid(),
      type: "step",
      x: 460,
      y: 260,
      label: "Adds to Cart",
      detail: "Customer selects model, storage, color, and condition then adds to cart",
      actor: "system",
      tools: ["Shopify Cart"],
      sla: "Realtime",
    },
    {
      id: nid(),
      type: "step",
      x: 460,
      y: 380,
      label: "Proceeds to Checkout",
      detail: "Enters shipping address, selects payment method, and applies any discount code",
      actor: "system",
      tools: ["Checkout Gateway"],
      sla: "10 min",
    },
    {
      id: nid(),
      type: "decision",
      x: 460,
      y: 510,
      label: "How is the customer paying?",
      detail: "Payment method determines the next verification steps",
      actor: "system",
      tools: ["Payment Router"],
    },
    {
      id: nid(),
      type: "sub",
      x: 80,
      y: 510,
      label: "COD: Verify by Phone",
      detail: "Agent calls customer to confirm the Cash on Delivery order is genuine",
      actor: "revibe",
      tools: ["Zendesk Talk", "admin.revibe.me"],
      sla: "2 hours",
      internalStage: "Pending COD Call",
      externalStage: "Order Verification",
      agentSteps: [
        "1. Open Zendesk Talk and dial customer phone number",
        "2. Confirm recipient name, delivery address, and order total",
        "3. If confirmed, click 'Approve COD' in admin portal",
      ],
    },
    {
      id: nid(),
      type: "decision",
      x: 80,
      y: 650,
      label: "Customer confirms?",
      detail: "Does the customer pick up and confirm they placed this order?",
      actor: "revibe",
      sla: "24 hours",
    },
    {
      id: nid(),
      type: "fail",
      x: -50,
      y: 790,
      label: "Order Cancelled",
      detail: "Customer did not confirm — order is automatically cancelled",
      actor: "system",
      tools: ["Shopify", "Klaviyo"],
      internalStage: "Cancelled — Unreachable",
      externalStage: "Cancelled",
    },
    {
      id: nid(),
      type: "sub",
      x: 860,
      y: 510,
      label: "Installment: ID Verification",
      detail: "Customer submits national ID for Tamara / Tabby / Revibe installment verification",
      actor: "revibe",
      tools: ["Tamara Portal", "Tabby KYC"],
      sla: "30 min",
      internalStage: "KYC Verification",
      externalStage: "ID Check",
      agentSteps: [
        "1. Check Tamara dashboard for pre-approval token",
        "2. Validate ID match with credit bureau status",
      ],
    },
    {
      id: nid(),
      type: "step",
      x: 460,
      y: 690,
      label: "Operations Assigns a Supplier",
      detail: "The Revibe operations team identifies the best supplier for this product",
      actor: "revibe",
      tools: ["Buybox Engine", "admin.revibe.me"],
      sla: "1 hour",
      internalStage: "Supplier Allocation",
      externalStage: "Processing",
    },
    {
      id: nid(),
      type: "decision",
      x: 460,
      y: 820,
      label: "Is the product available?",
      detail: "Supplier confirms they have the exact model, color, and condition in stock",
      actor: "seller",
      tools: ["Supplier Portal"],
      sla: "12 hours",
    },
    {
      id: nid(),
      type: "decision",
      x: 860,
      y: 820,
      label: "Can an alternative be offered?",
      detail: "Operations checks if another supplier or similar product is available",
      actor: "revibe",
      tools: ["Inventory Search"],
      sla: "4 hours",
    },
    {
      id: nid(),
      type: "fail",
      x: 860,
      y: 960,
      label: "Order Cancelled & Refunded",
      detail: "No suitable product found — customer is refunded",
      actor: "system",
      tools: ["Stripe", "Checkout.com"],
      internalStage: "Refunded — Stockout",
      externalStage: "Refunded",
    },
    {
      id: nid(),
      type: "step",
      x: 1100,
      y: 710,
      label: "Offer Alternative to Customer",
      detail: "Customer is contacted with a replacement option (different color, storage, or supplier)",
      actor: "revibe",
      tools: ["WhatsApp Business", "Zendesk"],
      sla: "2 hours",
      internalStage: "Alternative Offer Sent",
      externalStage: "Options Available",
    },
    {
      id: nid(),
      type: "step",
      x: 460,
      y: 960,
      label: "Supplier Confirms the Order",
      detail: "Supplier locks in the device — confirmed date is recorded",
      actor: "seller",
      tools: ["Supplier OMS"],
      sla: "6 hours",
      internalStage: "Confirmed by Supplier",
      externalStage: "Order Confirmed",
    },
    {
      id: nid(),
      type: "step",
      x: 460,
      y: 1080,
      label: "Device Undergoes Quality Check",
      detail: "QC team inspects: screen, battery health, buttons, cameras, and IMEI verification",
      actor: "seller",
      tools: ["QC Diagnostics App", "IMEI Scanner"],
      sla: "12 hours",
      internalStage: "In QC Diagnostics",
      externalStage: "Quality Inspection",
      agentSteps: [
        "1. Scan physical IMEI and match with order record",
        "2. Run 40-point diagnostic hardware checklist",
        "3. Verify battery health exceeds 85%",
        "4. Wipe and factory reset device",
      ],
    },
    {
      id: nid(),
      type: "decision",
      x: 120,
      y: 1080,
      label: "Installment order?",
      detail: "Does this order require a device lock for payment protection?",
      actor: "system",
      tools: ["MDM System"],
    },
    {
      id: nid(),
      type: "sub",
      x: 120,
      y: 1220,
      label: "Install Device Lock",
      detail: "Anti-theft lock is installed on the device to protect installment payments",
      actor: "seller",
      tools: ["Samsung Knox / MDM"],
      sla: "1 hour",
      internalStage: "MDM Profile Provisioned",
      externalStage: "Preparing Shipment",
    },
    {
      id: nid(),
      type: "step",
      x: 460,
      y: 1220,
      label: "Courier Picks Up the Device",
      detail: "Shipment created with courier (Aramex, DHL, SMSA, Naqel, UPS, or others)",
      actor: "carrier",
      tools: ["Aramex Gateway", "SMSA Portal"],
      sla: "24 hours",
      internalStage: "AWB Generated & Handover",
      externalStage: "Handed to Courier",
    },
    {
      id: nid(),
      type: "step",
      x: 460,
      y: 1340,
      label: "Device In Transit to Customer",
      detail: "Tracking number is shared — customer can follow their delivery live",
      actor: "carrier",
      tools: ["Courier Live Tracking"],
      sla: "24-48 hours",
      internalStage: "In Transit",
      externalStage: "Shipped — In Transit",
    },
    {
      id: nid(),
      type: "decision",
      x: 460,
      y: 1470,
      label: "Does the customer accept delivery?",
      detail: "Courier delivers the package to the customer's address",
      actor: "carrier",
      sla: "24 hours",
    },
    {
      id: nid(),
      type: "ok",
      x: 410,
      y: 1610,
      label: "Order Delivered Successfully",
      detail: "Customer receives their device — delivery date is recorded",
      actor: "carrier",
      tools: ["Proof of Delivery (POD)"],
      internalStage: "Delivered & Completed",
      externalStage: "Delivered",
    },
    {
      id: nid(),
      type: "fail",
      x: 770,
      y: 1470,
      label: "Customer Refused Delivery",
      detail: "Device is returned to sender — a claim process may follow",
      actor: "carrier",
      tools: ["Courier Return Portal"],
      internalStage: "RTO — Returned to Origin",
      externalStage: "Delivery Failed",
    },
    {
      id: nid(),
      type: "step",
      x: 120,
      y: 1610,
      label: "Payment Settled with Supplier",
      detail: "Finance team processes supplier payment — tracked as Paid, Waived, or Backlog",
      actor: "revibe",
      tools: ["QuickBooks", "Payout Dashboard"],
      sla: "7 days",
      internalStage: "Finance Settled",
      externalStage: "Completed",
    },
  ];
}

export function getInitialConnections(): FlowConnection[] {
  return [
    { from: "n1", to: "n2", label: "", type: "" },
    { from: "n2", to: "n3", label: "", type: "" },
    { from: "n3", to: "n4", label: "", type: "" },
    { from: "n4", to: "n5", label: "", type: "" },
    { from: "n5", to: "n6", label: "Cash on Delivery", type: "camber" },
    { from: "n5", to: "n9", label: "Installments", type: "camber" },
    { from: "n5", to: "n10", label: "Card / Apple Pay / Prepaid", type: "cyes" },
    { from: "n6", to: "n7", label: "", type: "" },
    { from: "n7", to: "n8", label: "No", type: "cno" },
    { from: "n7", to: "n10", label: "Yes", type: "cyes" },
    { from: "n9", to: "n10", label: "Verified", type: "cyes" },
    { from: "n10", to: "n11", label: "", type: "" },
    { from: "n11", to: "n12", label: "Not available", type: "cno" },
    { from: "n11", to: "n15", label: "Available", type: "cyes" },
    { from: "n12", to: "n13", label: "No alternative", type: "cno" },
    { from: "n12", to: "n14", label: "Yes", type: "cyes" },
    { from: "n14", to: "n10", label: "Customer accepts", type: "camber" },
    { from: "n15", to: "n16", label: "", type: "" },
    { from: "n16", to: "n17", label: "", type: "" },
    { from: "n17", to: "n18", label: "Yes", type: "camber" },
    { from: "n17", to: "n19", label: "No", type: "cyes" },
    { from: "n18", to: "n19", label: "", type: "" },
    { from: "n19", to: "n20", label: "", type: "" },
    { from: "n20", to: "n21", label: "", type: "" },
    { from: "n21", to: "n22", label: "Delivered", type: "cyes" },
    { from: "n21", to: "n23", label: "Refused / Returned", type: "cno" },
    { from: "n22", to: "n24", label: "14-day warranty cleared", type: "cyes" },
  ];
}
