import { FlowNode, FlowConnection } from "./types";

let _nid = 100;
function nid(): string {
  return "n" + ++_nid;
}

export function getKBNodes(): FlowNode[] {
  _nid = 100;
  return [
    {
      id: nid(),
      type: "start",
      x: 500,
      y: 40,
      label: "Customer Files Warranty Claim",
      detail: "Customer reports a device defect or malfunction via Zendesk / Help Center",
      actor: "revibe",
      tools: ["Zendesk Portal", "Revibe Help Center"],
      sla: "Instant",
      internalStage: "Claim Ingested",
      externalStage: "Claim Received",
    },
    {
      id: nid(),
      type: "step",
      x: 500,
      y: 170,
      label: "Tier 1: Triage & Proof Review",
      detail: "Support reviews customer photos, video evidence, and purchase invoice (within 1-year warranty)",
      actor: "revibe",
      tools: ["Zendesk Ticket", "Shopify Orders"],
      sla: "4 hours",
      internalStage: "Triage & Validation",
      externalStage: "Under Review",
      agentSteps: [
        "1. Verify purchase date is within 12-month warranty",
        "2. Confirm IMEI matches original order invoice",
        "3. Review customer video showing described issue",
      ],
    },
    {
      id: nid(),
      type: "decision",
      x: 500,
      y: 310,
      label: "Is the issue covered under warranty?",
      detail: "Checks for accidental damage, liquid ingress, or unauthorized third-party repairs",
      actor: "revibe",
      sla: "2 hours",
    },
    {
      id: nid(),
      type: "fail",
      x: 880,
      y: 310,
      label: "Claim Rejected (Out of Scope)",
      detail: "Customer notified of warranty exclusion (e.g. cracked screen or water damage) with repair quote",
      actor: "revibe",
      tools: ["Zendesk Email"],
      internalStage: "Claim Denied — Out of Scope",
      externalStage: "Claim Rejected",
    },
    {
      id: nid(),
      type: "step",
      x: 500,
      y: 460,
      label: "Generate Return Courier Waybill",
      detail: "Prepaid reverse pickup AWB generated and courier booked to retrieve faulty item",
      actor: "carrier",
      tools: ["Aramex Reverse Logistics", "DHL"],
      sla: "24 hours",
      internalStage: "Reverse AWB Created",
      externalStage: "Courier Pickup Scheduled",
    },
    {
      id: nid(),
      type: "step",
      x: 500,
      y: 590,
      label: "LAB Technical Diagnostics",
      detail: "Hardware engineering inspects device motherboard, battery calibration, and display integrity",
      actor: "seller",
      tools: ["Revibe LAB Diagnostics", "Blackbelt QC"],
      sla: "24 hours",
      internalStage: "In Technical LAB Inspection",
      externalStage: "Diagnostics in Progress",
      agentSteps: [
        "1. Receive package and record unboxing video",
        "2. Test hardware components with diagnostics software",
        "3. Confirm whether issue is repairable or requires replacement",
      ],
    },
    {
      id: nid(),
      type: "decision",
      x: 500,
      y: 730,
      label: "Can the item be repaired?",
      detail: "Determines whether a technician repair or unit replacement is required",
      actor: "seller",
      sla: "6 hours",
    },
    {
      id: nid(),
      type: "step",
      x: 180,
      y: 730,
      label: "Certified Part Repair & Recalibration",
      detail: "Defective component replaced with genuine certified parts; full QC re-tested",
      actor: "seller",
      tools: ["LAB Workbench", "Cleanroom"],
      sla: "24 hours",
      internalStage: "Repaired & Re-QC Passed",
      externalStage: "Repair Completed",
    },
    {
      id: nid(),
      type: "step",
      x: 820,
      y: 730,
      label: "Allocate Replacement Unit",
      detail: "Matching refurbished device allocated from inventory or supplier buybox",
      actor: "revibe",
      tools: ["admin.revibe.me", "Inventory OMS"],
      sla: "12 hours",
      internalStage: "Replacement Allocated",
      externalStage: "Replacement Arranged",
    },
    {
      id: nid(),
      type: "step",
      x: 500,
      y: 880,
      label: "Dispatch Device Back to Customer",
      detail: "Secure packaging and expedited courier shipment back to customer's address",
      actor: "carrier",
      tools: ["Aramex Express"],
      sla: "24-48 hours",
      internalStage: "Resolved — In Transit Back",
      externalStage: "Device Dispatched",
    },
    {
      id: nid(),
      type: "ok",
      x: 500,
      y: 1020,
      label: "Warranty Claim Resolved & Closed",
      detail: "Customer confirms receipt of working device; feedback survey sent",
      actor: "revibe",
      tools: ["Zendesk CSAT", "Klaviyo"],
      internalStage: "Claim Closed — Success",
      externalStage: "Completed",
    },
  ];
}

export function getKBConnections(): FlowConnection[] {
  return [
    { from: "n101", to: "n102", label: "", type: "" },
    { from: "n102", to: "n103", label: "", type: "" },
    { from: "n103", to: "n104", label: "Physical / Liquid Damage", type: "cno" },
    { from: "n103", to: "n105", label: "Covered Defect", type: "cyes" },
    { from: "n105", to: "n106", label: "Device Received at LAB", type: "cyes" },
    { from: "n106", to: "n107", label: "Inspection Done", type: "" },
    { from: "n107", to: "n108", label: "Yes (Repairable)", type: "cyes" },
    { from: "n107", to: "n109", label: "No (Replace Unit)", type: "camber" },
    { from: "n108", to: "n110", label: "Ready to Ship", type: "cyes" },
    { from: "n109", to: "n110", label: "Unit Picked", type: "cyes" },
    { from: "n110", to: "n111", label: "Delivered to Customer", type: "cyes" },
  ];
}
